/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.0-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
