/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v1.33-11-ga391d23-5.0"
#endif /* AVUTIL_FFVERSION_H */
