/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105350-g3c804fdd4a-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
